### ISSUE TITLE
Air quality calculation is faulty as Airly uses CAQI index not AQI

### ISSUE THREAD

**Issue by cpiekacz** [beniamin-rychter-coderslab/homebridge-airly#2]
[Airly uses CAQI index](https://airly.eu/en/everything-you-should-know-about-air-pollution/#caqi) (which ranges between 0 and 100) and not AQI (which ranges between 0 and 300+), so you have to calculate the air quality differently.

**Comment by beniamin-rychter-coderslab** [comment]
@cpiekacz You are right. I didn't check that :) Thanks! In next update I'll change that.
